import { readFileSync, writeFileSync } from 'node:fs'
import { resolve } from 'node:path'

const root = resolve(import.meta.dirname, '..')
const character = readFileSync(resolve(root, 'assets/rei-character-cutout.webp')).toString('base64')
const favicon = `
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 64 64">
  <rect width="64" height="64" rx="13" fill="#081521"/>
  <path d="M9 12h46v3H9zm0 37h46v3H9z" fill="#8bd8ef"/>
  <circle cx="32" cy="32" r="14" fill="none" stroke="#8bd8ef" stroke-width="2"/>
  <path d="M32 18v28M18 32h28" stroke="#8bd8ef" stroke-opacity=".35"/>
  <circle cx="32" cy="32" r="5" fill="#c93455"/>
  <path d="M27 8h10l3 4H24z" fill="#eaf9ff"/>
</svg>`

const output = `// Generated by scripts/sync-art.mjs from the optimized project asset.\n` +
  `export const SKIN_ART = 'data:image/webp;base64,${character}'\n` +
  `export const SKIN_FAVICON = \`data:image/svg+xml,\${encodeURIComponent(\`${favicon}\`)}\`\n`

writeFileSync(resolve(root, 'shared/art.js'), output)
console.log('Synced shared/art.js from assets/rei-character-cutout.webp')
